### ISSUE TITLE
Multiline execution fails on unterminated quotes

### ISSUE THREAD

**Issue by gorban** [habamax/vim-evalvim#2]
Issue running commands with multiline strings. Issue occurs regardless of single or double quotes.

Tested with keybindings as listed in the [README.md, #Usage](https://github.com/habamax/vim-evalvim?tab=readme-ov-file#usage):\
&nbsp; **\<leader>vap** - Run this plugin with all the current paragraph

Content in Vim buffer:
```bash
echo "line 1
line 2
line 3"
```

Expected result:
> line 1
  line 2
  line 3

Actual result is an Error:
> Error detected while processing function evalvim#run:
  line &nbsp; 32:
  E114: Missing double quote: "line 1

For comparison running directly in terminal works as expected:
```bash
bash -c 'echo "line 1
line 2
line 3" '
```

I am on evalvim.vim,
```bash
Version:      1.0
```

`:version`
```bash
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 21 2024 12:49:18)
macOS version - x86_64
Included patches: 1-193
...
Huge version without GUI.
...
```

**Comment by habamax** [comment]
It is not supposed to run arbitrary shell commands, this is about vimscript evaluation, in other words, running vimscript.

Nowadays it is not needed though, we have `:source` that could be run on a range of lines as in `:%source` or `:'<,'>source`, which one can upgrade to an operator:

```
vim9script

# source vimscript (operator)
def SourceVim(...args: list<any>): any
    if len(args) == 0
        &opfunc = matchstr(expand('<stack>'), '[^. ]*\ze[')
        return 'g@'
    endif
    if getline(1) =~ '^vim9script$'
        vim9cmd :'[,']source
    else
        :'[,']source
    endif
    return ''
enddef
nnoremap <silent> <expr> <space>v SourceVim()
xnoremap <silent> <expr> <space>v SourceVim()
nnoremap <silent> <expr> <space>vv SourceVim() .. '_'
```

**Comment by habamax** [comment]
For the arbitrary terminal commands you can come up with something like https://github.com/habamax/.vim/blob/master/autoload/term.vim#L2-L5

Or https://github.com/habamax/vim-sendtoterm
